![imagen](./img/ejercicios.png)

In [69]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [70]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
print(my_array[::-2])

[9 7 5 3 1]


In [72]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [73]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [75]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
print(my_array[2::-1])

[2 1 0]


In [77]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [78]:
np.sort(my_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [80]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [81]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [82]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [83]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [84]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [85]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [86]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [87]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [88]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [89]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [90]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [91]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [92]:
x == "Loro"

array([ True, False, False,  True, False])

In [93]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [94]:
print(np.where(x== "Loro")[0])

[0 3]


In [95]:
print(np.where(x == "Loro")[0])

[0 3]


In [96]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [97]:
# np.where(x == "Loro", x, np.nan)

In [98]:
np.where(x=="Loro")

(array([0, 3]),)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [99]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [100]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [101]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [102]:
x = np.zeros(10)
x.nbytes

80

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [103]:
x = np.arange(10,50)[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [104]:
x = np.array( [1,2,0,0,4,0])
x

array([1, 2, 0, 0, 4, 0])

In [108]:
x[x!=0]

array([1, 2, 4])

In [109]:
x!=0

array([ True,  True, False, False,  True, False])

In [111]:
np.where(x!=0)[0]

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [112]:
x= np.random.rand(100).reshape(10,10)
x

array([[0.10619426, 0.88470796, 0.67627757, 0.58072851, 0.84940507,
        0.4827825 , 0.26510829, 0.31995657, 0.03217765, 0.53549207],
       [0.83519541, 0.71620829, 0.48494532, 0.69540457, 0.90906071,
        0.72677136, 0.50783694, 0.03202744, 0.34708633, 0.50534401],
       [0.68426255, 0.13873794, 0.57762574, 0.74388188, 0.5907687 ,
        0.49411099, 0.90525968, 0.24032893, 0.84567444, 0.67998944],
       [0.62522493, 0.01056496, 0.08940988, 0.92498608, 0.43581958,
        0.10139715, 0.37360148, 0.99587579, 0.02926608, 0.6166735 ],
       [0.33828374, 0.24288789, 0.87380455, 0.25523886, 0.67807645,
        0.32294253, 0.96261579, 0.08526244, 0.55659173, 0.91630886],
       [0.1559171 , 0.02520366, 0.3487333 , 0.58283129, 0.46175875,
        0.28754476, 0.37779496, 0.45213696, 0.40537684, 0.68536954],
       [0.50992102, 0.01174782, 0.99034092, 0.99681799, 0.53147949,
        0.53728876, 0.03953119, 0.24511263, 0.02544419, 0.54762181],
       [0.6338277 , 0.44464619, 0.5329775

In [114]:
print(np.min(x))

0.010564960210771801


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [119]:
print(np.mean(np.random.rand(30)))

0.46345999714092784


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [126]:
x = np.random.randint(1,20,(5,5))
y = (x - np.mean(x) )/ np.std(x)
print(np.mean(y))
print(np.mean(y))

-6.217248937900877e-17
-6.217248937900877e-17


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [133]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
x[x>3]=4
x

array([0, 1, 2, 3, 4, 4, 4, 4, 4, 4, 4])